version = 1

exclude_patterns = [
  "html/js/**"
  "**/node_modules/"
  "templates/**"
  "releases/**"
  "sql/preapril2020migration/**"
]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/gochan-org/gochan"
  dependencies_vendored = false

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "sql"
enabled = true
