version = 1

exclude_patterns = [
  "html/js/**",
  "**/node_modules/",
  "templates/**",
  "releases/**",
  "sql/preapril2020migration/**",
  "frontend/tests/coverage/**"
]

test_patterns = [
  "frontend/tests/*.test.ts",
  "frontend/ts/**/*.ts",
  "**/*_test.go"
]

[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
    environment = ["jquery"]

[[analyzers]]
name = "typescript"
enabled = true
  [analyzers.meta]
    environment = ["jquery"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/gochan-org/gochan"
  dependencies_vendored = false

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "sql"
enabled = true
