services:
  gochan:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - GOCHAN_DBTYPE=mysql
        - GOCHAN_DBHOST=gochan-mysql:3306
    container_name: gochan-server
    ports:
      - "80:80"
    volumes:
      - ./volumes/gochan/log:/var/log/gochan
      - ./volumes/gochan/www:/var/www/gochan
    networks:
      - gochan-bridge
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0-bookworm
    container_name: gochan-mysql
    tty: true
    expose:
      - "3306"
    networks:
      - gochan-bridge
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gochan
      - MYSQL_USER=gochan
      - MYSQL_PASSWORD=gochan
    volumes:
      - ./volumes/mysql:/var/lib/mysql

networks:
  gochan-bridge:
    name: gochan-bridge
    driver: bridge
