# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '41 5 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        days-before-issue-stale: 150
        days-before-issue-closed: 15
        days-before-pr-stale: -1
        days-before-pr-close: -1
        exempt-issue-labels: ongoing,bug
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open for 150 days with no activity.'
        close-issue-message: "This issue was closed because it has been inactive for 15 days since being marked as stale."
        stale-pr-message: 'This pull request is stale because it has been open for 150 days with no activity.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
